
steps:

### Build

  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          docker build -t eu.gcr.io/$PROJECT_ID/cloud_app:${BRANCH_NAME}-${SHORT_SHA} .



### Test


### Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          docker push eu.gcr.io/$PROJECT_ID/cloud_app:${BRANCH_NAME}-${SHORT_SHA}



### Deploy
  - id: 'deploy'
    name: 'eu.gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud run deploy cloud_app \
            --image eu.gcr.io/$PROJECT_ID/cloud_app:${BRANCH_NAME}-${SHORT_SHA} \
            --platform managed \
            --region europe-west2 \
            --allow-unauthenticated
